# Site settings
title: AL Development Collection
description: AI Native AL Development toolkit for Microsoft Dynamics 365 Business Central
baseurl: "/AL-Development-Collection-for-GitHub-Copilot"
url: "https://javiarmesto.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.8.2

# Color scheme
color_scheme: dark

# Logo
logo: "/assets/images/logo.png"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive
nav_enabled: true

# Aux links
aux_links:
  "View on GitHub":
    - "https://github.com/javiarmesto/AL-Development-Collection-for-GitHub-Copilot"
  "Download Release":
    - "https://github.com/javiarmesto/AL-Development-Collection-for-GitHub-Copilot/releases/latest"

# Footer
footer_content: 'Copyright &copy; 2025 Javier Armesto González. Licensed under the <a href="https://github.com/javiarmesto/AL-Development-Collection-for-GitHub-Copilot/blob/main/LICENSE">MIT License</a>.'

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: purple

# Mermaid diagrams
mermaid:
  version: "10.6.1"

# Heading anchors
heading_anchors: true

# Collections
collections:
  instructions:
    permalink: "/:collection/:path/"
    output: true
  prompts:
    permalink: "/:collection/:path/"
    output: true
  chatmodes:
    permalink: "/:collection/:path/"
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "instructions"
      type: "instructions"
    values:
      layout: default
      nav_order: 2
  - scope:
      path: "prompts"
      type: "prompts"
    values:
      layout: default
      nav_order: 3
  - scope:
      path: "chatmodes"
      type: "chatmodes"
    values:
      layout: default
      nav_order: 4

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .bundle/
  - .git/
  - .github/
  - archive/
  - validate-al-collection.js
  - package.json
  - package-lock.json
  - "*.instructions.md"
  - "*.prompt.md"
  - "*.chatmode.md"
